apiVersion: v1
name: reactioncommerce
home: https://reactioncommerce.com/
version: 0.1.0
appVersion: 3.7.1
description: Reaction Commerce is an API-first, modular commerce 
 stack made for ambitious brands and retailers. Reaction’s
 service-based architecture is built to deliver flexibility and
 freedom at scale.
sources:
  - https://github.com/reactioncommerce/reaction
  - https://github.com/reactioncommerce/reaction-admin
  - https://github.com/reactioncommerce/reaction-identity
  - https://github.com/reactioncommerce/example-storefront
maintainers:
  - name: dcrdev
    email: dominic@dcrdev.com