{{- if .Values.admin.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "reactioncommerce.fullname" . }}-admin
  labels:
    app: {{ template "reactioncommerce.name" . }}
    component: admin
    chart: {{ template "reactioncommerce.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- if .Values.admin.service.annotations }}
{{ toYaml .Values.admin.service.annotations | trim | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.admin.service.type }}
  selector:
    app: {{ template "reactioncommerce.name" . }}
    component: admin
    release: {{ .Release.Name }}
  ports:
    - name: "admin"
      port: 4080
      targetPort: 4080
    - name: "inspector"
      port: 9231
      targetPort: 9229
{{- end }}
